### ISSUE TITLE
Fix header logo darkmode

### ISSUE THREAD

**Issue by tarjelavik** [uib-ub/exhibition-landsloven-nextra#22]
The logo is a svg file, and the darkmode is not working properly. The logo does not flip. Convert it to a React component that respects the darkmode.

**Comment by espenmn** [comment]
I made a workaround (two alternative logos, one for 'dark' and one for 'white'.
Theoretically, the colors can be set with CSS, but for some reason this does not work.

Check the CSS file and you will see that the separator in breadcrumbs is set (and working) there.

PS: tried   with path, stroke,  fill etc.

**Comment by tarjelavik** [comment]
I think your solution is fine. The react way is to create a component and let it pick up currentColor. I added some logos from another repo, mostly as examples. It is a bit of work "converting" svgs to react components.
