### ISSUE TITLE
Favicon desktop icon (etc)

### ISSUE THREAD

**Issue by espenmn** [uib-ub/exhibition-landsloven-nextra#29]
Should we have a favicon?
If so, what ( law icon / 750 ? )

Is _app.js the correct place to define it (or can it be done in config files ?

https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons

**Comment by espenmn** [comment]
Maybe it can be done by inserting into head (in theme.config.js) 

    head: (
        <React.Fragment>
           stuff here
        </React

**Comment by espenmn** [comment]
Maybe fixed, but need feedback on 'which icon'

**Comment by espenmn** [comment]
For now, I have added an icon based on the 'm' from the banner

**Comment by tarjelavik** [comment]
Good for now. The "styringsgruppe" could have ideas, but probably not :-/.
