### ISSUE TITLE
Automatic generation of config files (?)

### ISSUE THREAD

**Issue by espenmn** [uib-ub/exhibition-landsloven-nextra#37]
Brainstorming: Look at how the 'sitemap.xml' files gets generated. 
Maybe it could be possible (easy) to generate different meta / config files so we dont have to do 'duplicate work' .

In other words: We have a 'postbuild' script that generates  (the static file) 'some-config' based on contents of 'some-other-config-file' (or contents of folders) ?

**Comment by tarjelavik** [comment]
Must be prebuild at least, since the generated files is used in the build process :-). 

Also brainstorming, mdx could have frontmatter with image link, ingress, etc. that is picked up in a prebuild step. Yeah, possible.

**Comment by tarjelavik** [comment]
Fixed in the latest commits. Script creates a siteFrontmatter.json based on content in the mdx files. siteFrontmatter and _meta files are now the only ones that is used. Extra work eliminiated.
