### ISSUE TITLE
Find out where 'class' is wrongly declared

### ISSUE THREAD

**Issue by espenmn** [uib-ub/exhibition-landsloven-nextra#47]
I have not found out where it comes from, but there is a warning:

Warning: Invalid DOM property `class`. Did you mean `className`?

Could it be in an icon or similar?

**Comment by tarjelavik** [comment]
I have done a search-n-replace earlier :-). Shouldn't be too difficult to find.

**Comment by espenmn** [comment]
I think this is fixed now
