### ISSUE TITLE
Make sure 'alt tag is defined if image is defined'

### ISSUE THREAD

**Issue by espenmn** [uib-ub/exhibition-landsloven-nextra#54]
Brainstormning

Should we introduce an error if alt tag is not defined, but image is in the components?

Alternatively: is there a way to make 'alt' required, but only when image is present?

**Comment by tarjelavik** [comment]
Blocked builds are a bigger annoyance i think. Some images can have empty alt if context supplies text. A hard one, but we will have a accessibility check before launch, where we can find missing alt-s.
