### ISSUE TITLE
Kommentarer til under-text bilder fra landsloven-nextra

### ISSUE THREAD

**Issue by alexandros1702** [uib-ub/exhibition-landsloven-nextra#89]
https://exhibition-landsloven-nextra-git-fix-images-ratio-918273-uib-ub.vercel.app/arvetallet/tilgave
Tar dette som eksempel for et gjennomgående problem: Bilder i landscape format må for det meste var over teksten - og teksten sikkert må settes å ha mindre fonts?

Her er et eksempel av et landscape bilde som ikke trenger å bli plassert over, hvis bokstavene blir desidert mindre og bilde tar mye større plass:
https://exhibition-landsloven-nextra-git-fix-images-ratio-918273-uib-ub.vercel.app/landsleiebolken/tunet
Samme her: https://exhibition-landsloven-nextra-git-fix-images-ratio-918273-uib-ub.vercel.app/kjoepebolken/vekter
Men til og med for disse to, kan det være like greit å sette de over teksten.

Ellers var alt annet bra - incredibile videtu!!

**Comment by tarjelavik** [comment]
#96 retter det meste av dette. Har tatt noen avgjørelser på styling, men nå er det litt mer konsistent. Fjerne det meste av Spacer, som jeg synes gjør det mer lesbart. Luft skal uansett styres av komponentene.

**Comment by tarjelavik** [comment]
Jeg tok meg friheten til å merge... Så vi kan se på det og eventuelt lage nye saker på endringsønsker.
