### ISSUE TITLE
Kommentarer til visning av diplom og andre mss fra marcus

### ISSUE THREAD

**Issue by alexandros1702** [uib-ub/exhibition-landsloven-nextra#95]
Jeg tror at alle vinduene som genereres fra marcus urler burde vises med gjenstanden på toppen og forklarende teksten under.

Er dette noe som kan ordnes til i morgen kl 10:30?

**Comment by tarjelavik** [comment]
Fikset i siste pull request. Så bør være klar 16.27 i dag. I prod :-)
